### ISSUE TITLE
[3.0] Remove jQuery

### ISSUE THREAD

**Issue by milesj** [titon/toolkit#100]
Look into removing jQuery as a dependency. In a perfect world, we would use ES6 and vanilla JS.

**Comment by TraderStf** [comment]
FYI
http://zeptojs.com
Zepto is a minimalist JavaScript library for modern browsers with a largely jQuery-compatible API. If you use jQuery, you already know how to use Zepto.

**Comment by milesj** [comment]
Yeah, I'm aware of Zepto. However, Toolkit 3.0 is already under heavy development and will have *no* dependencies, as we are utilizing ES6 features and polyfills. Most of the jQuery functionality has already been replaced.

**Comment by milesj** [comment]
jQuery has been removed from 3.0 thus far. Will close this ticket.
