### ISSUE TITLE
Tabs component - ajaxing in content no longer working

### ISSUE THREAD

**Issue by mooror** [titon/toolkit#105]
Hey there guys, first off I want to thank you so much for creating this wonderful kit. It works great and is really bloat free. Keep it up. Second, I just wanted to inform you that I can not get the ajax feature working with the tabs component. I'm using brackets built in server and created a file called ajax at the root of my project. However when I use you tabs ajax example and add "../ajax/relatedPosts.ajax" as the href, it doesn't bring in the content. I opened up the chrome developer tools and found that the file path is correct but no contents are loading in. Please get back to me as soon as you can.

**Comment by milesj** [comment]
In 2.0, we made a change to how our content is detected by require AJAX URLs to be absolute. Either using the fully qualified URL, or starting with a forward slash.

http://titon.io/en/toolkit/2.1.0/development/js/usage#dynamic-content-loading

That might be the issue as you are using relative paths.

**Comment by milesj** [comment]
Were you able to solve this?

**Comment by milesj** [comment]
Going to assume this is fixed. Closing.
