### ISSUE TITLE
[2.1] stopScroll option doesn't work on mobile

### ISSUE THREAD

**Issue by flashios09** [titon/toolkit#111]
Hi @milesj ,

I'm trying the toolkit **offCanvas** component(using it as mobile/tablet menu), the **stop scroll** option (http://titon.io/en/toolkit/2.1.0/components/off-canvas#options) is only working on a desktop browser(using the **.no-scroll** class added to the body) but not on a mobile browser(tested on Safari+Chrome iPhone iOS 8) !

I think that must be an extra div(like a transparent mask hidden by default) displayed when the menu is open to avoid the scroll. What do you think ?

**Comment by milesj** [comment]
Yeah this has been an issue for a long time. It's support has varied between browsers and I haven't found a CSS only solution yet. But, it has been a while since I last looked into it so maybe things have changed since.

**Comment by flashios09** [comment]
So what do you suggest to fix it ?

**Comment by milesj** [comment]
Don't have one off the top of my head but there may be some trick I haven't tried yet.

**Comment by flashios09** [comment]
Ok i will try to fix it and post my solution here :)

**Comment by milesj** [comment]
You had a chance to look at this? Going to try and tackle it later, but if you have any info, that would be great!

**Comment by milesj** [comment]
I found a temporary fix but it's not perfect. I don't think there is a 100% perfect way of doing this as mobile devices are weird about it.
