### ISSUE TITLE
Merge with SemanticUI

### ISSUE THREAD

**Issue by Anachron** [titon/toolkit#115]
Hey there,

couldn't this be merged with ]SemanticUI](http://semantic-ui.com/)?
Or at least help each other?

SemanticUI uses LESS, Titon uses SCSS. Both have requests to support the other language.
I think there is some benefit you both can get from it.

@jlukic
FYI.

**Comment by milesj** [comment]
Semantic UI has a complete opposite approach to how their framework is designed and the philosophies between the two simply wouldn't mesh. I don't see this ever really happening.
