### ISSUE TITLE
tition.io - 2015-03-30 - Miscellaneous Remarks

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#118]
If it is ok with you, I will list and add all the tiny remarks, problems on titon.io, major ones will have their own message/issue/thread.

Or perhaps a new thread by day, so can be closed when solved, probably easier to manage.

No need to answer to these remarks, treat what you want.
I make all tests in latest Mac Yosemite, Safari, plugin off, gadget... If you want specific tests on other browser...

<h3>2015-03-30</h3>

<b>— Google Site Verification —</b>
<meta name="google-site-verification" content="SAH-N1cfX_4lSB-WmU6bm-8GvfbtnJzvORCfQKFL3Us">
Useless, need to be check only once, then can be deleted, code is available in Dashboard.
support.google.com/webmasters/answer/35179

<b>— og:description —</b>
<meta property="og:description" content=""> is empty.

<b>— Google font and analytics —</b>
They can dramatically slow down your site, you can copy them locally, specially the font.
For analytics, though, you'll have to track any changes, it is not dramatic, I was doing it every month.
An automatic online tool (or curl) can probably warn when it is updated.

<b>— style.min.css —</b>
http://csslint.net/ reports nothing but Mac Safari Inspector reports line 207.
<pre>207 */
208 @font-face {
209...
</pre>
/!\ (5) Unexpected CSS token: :
Compared to [w3org](http://www.w3.org/TR/css3-fonts/#font-face-rule) and [font-face.com](http://www.font-face.com/#green_content) it seems they do not use quotes at all.

<b>— popover without arrow-triangle or not shown —</b>
http://titon.io/en/toolkit
In block 'Powerful UI Components', if you move the mouse pointer a bit over a pink line:

1. sometimes, the popover is without the 'triangle', it is just a rectangle.

2. sometimes, when the mouse is going in-out-in between 2 pink lines, the popover does not appear at all, even moving around the same line (without going out) where it should be. Must go out and come back over to see it.

I think both are linked to speed problem, as soon as you move a bit to fast the mouse pointer.

<b>— a href link on 2 lines —</b>
Seems strange so many a href are on 2 lines (end of first line is ascii 13), this is reported by validator as return must be encoded as %0D... why on 2 lines...

`<a href="/en/toolkit/2.1.0"`
`/releases/2.1" class="button large">`

<b>— main class="body" unknown or malformed —</b>
Can't find why, BBEdit reports this error, e.g. http://titon.io/en/toolkit
Could it be because it is in both <i>style.min.css</i> and <i>toolkit.min.css</i>

On http://titon.io/en/toolkit
For readability, I would put the 2 blocks of code at the end one after another, as even with a large window, the left one is still with wrapped lines.

<b>— 🇺🇸 ENGLISH 🇬🇧 —</b>
<i>addons</i> - Safari spell checker either <i>add ons</i> or <i>add-ons</i>.

**Comment by TraderStf** [comment]
<b>— Error 404 —</b>
<pre>
"Status","URL","Appears on","Link Text"
"404 not found","http://titon.io/en/toolkit/2.1.0/components/base","35 occurrences over more than one page",""
"404 not found","http://titon.io/en/toolkit/2.1.0/setup/rtl","http://titon.io/en/toolkit/2.1.0/setup/custom-builds",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/input","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/drop","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/flyout","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/carousel","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/showcase","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/css/grid","http://titon.io/en/toolkit/2.1.0/development/css/base",""
"404 not found","http://titon.io/en/toolkit/2.1.0/development/installing","http://titon.io/en/toolkit/2.1.0/development/rtl",""
</pre>

**Comment by TraderStf** [comment]
— demo.titon.io —
Site links can not be verified as there is no 'visible' links for tools... Is it the same for search engines ?
Add a noscript? html block?

**Comment by milesj** [comment]
The official titon.io site is getting a redesign, so I'm not too worried about minor issues right now. 

The demos however, I will look into.

**Comment by milesj** [comment]
Going to close this for now since the official titon.io is being redesigned.
