### ISSUE TITLE
demo.titon.io - Meta 'viewport' - 'minimal-ui' not recognized

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#119]
All pages of course, get this in Mac Safari.

[Error] Viewport argument key "minimal-ui" not recognized and ignored. (demo.titon.io, line 6)

**Comment by milesj** [comment]
This is an iOS specific meta keyword. I'll look into it more.

**Comment by milesj** [comment]
Removed it. Seems like it was removed from iOS8 as well.
