### ISSUE TITLE
demo.titon.io - 2015-03-30 - Miscellaneous Remarks

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#120]
Only tested on Mac Safari, did not test other browsers.
I have used different zoom levels to reduce the size of some captures.

<h3>— Code —</h3>

Is it normal that 4 lines have "a: a", same on left and right? (no need to answer)

`hasTransition: hasTransition,`
`isTouch: isTouch,`
`isRetina: isRetina,`
`transitionEnd: transitionEnd,`

<h3>— Divider —</h3>

Suggestion: add a Lorem line between each.

<h3>— Drop —</h3>

1) The first 3 blocks are without 1px clear-line between menu items.

Block 4, Drop Ups, has 1px clear-line in between each.
The highlighting of the current/selected menu item is not covering the full height, seems the text is not well vertically aligned, see capture.

![drophighlight](https://cloud.githubusercontent.com/assets/5954335/6899722/890e12e6-d702-11e4-9199-c092041be492.png)

2) Is it normal that some drop appears below or above the grey button?
Add a sentence explaining where it must appear, top-right, bottom-left...

3) Drop with Heading
The Heading line is the second line, see capture?

![dropheading](https://cloud.githubusercontent.com/assets/5954335/6899897/80416964-d703-11e4-805b-2d7a508bce48.png)

<h3>— Flew —</h3>

Some X+1 columnS are without S, eg "3 column".

1) Horizontal alignment. No grow. Base width.

Is it the good alignment, 1 of second line is not perfectly below 3 of first line?

![horizalign](https://cloud.githubusercontent.com/assets/5954335/6900037/3d76199e-d704-11e4-98d1-235d914a0ca8.png)

Same for "Vertical alignment. No grow. Base height."

2) Responsive sizes & breakpoints. Collapses on mobile (manual).
When width is small enough, the 1x3 cells (*oh) are changing to 3x1 cells.
But the first cell keeps its (*oh) original heigth, the one in 1x3, but the cell 2 and 3 have a height enough to display their content.

<blockquote>
Note - I need to make further tests, the explication above can be repeated.
But I had also the following, must try to find how exactly to reproduce this.
What's for sure that if you don't reload the page, the 3 cells are staying on one row (1x3) but their order is always changing as describe here after.

I will make a movie, because the cells are changing position, fake example: 123, enlarge, 213, reduce 312... Small capture just to illustrate, it is now right-left-content!
</blockquote>
![collapsecrazy](https://cloud.githubusercontent.com/assets/5954335/6901098/52859c72-d70b-11e4-93bd-5d44a8c1488c.png)

<h3>— Flyout —</h3>

1) Overlap
When the NTH sub-menu can not be displayed on the right because there is not enough space, it is drawn on the left, but it becomes over NTH-2 sub-menu.
Which seems very weird, as the NTH-2 sub-menu seems 'longer' and in this case with just 'numbers' as menu items, you have the illusion that NTH-2 sub-menu is made of "2 parts".

![menuoverlap](https://cloud.githubusercontent.com/assets/5954335/6900532/5fcb8bb6-d707-11e4-8e0a-d7640bc11873.png)

2) Zoom Change
Display Root show 1-2-3-1, now with the keyboard change the zoom, reduced.
The menus are staying, moving a bit everywhere... but who's stup-ID enough to do that 😜

3) Click Activated
With menus with only one background-color, this one can become really "crazy".
In this capture, 4-1-to-4-5 are not visible until the window's with is large enough to display both, i.e. 4-1-to-4-5 and on its right 4-6-to-4-8.
A menu 'block' like e.g. 4-6-to-4-8 can only be displayed entierely.

![flyoutclickcrazy](https://cloud.githubusercontent.com/assets/5954335/6900858/c784647e-d709-11e4-9c9c-aedd348fd478.png)

**Comment by milesj** [comment]
Thanks for the feedback. I'll update the demo site later today.

And to answer some of your questions.

Code
- The `a: a` format is because of RequireJS and the dependency loop. The variables are used throughout the rest of the library, not just in the `Toolkit` object.

Divider
- Added some spacing between the dividers.

Drop
1 - There are no dividing lines between each item, this is on purpose. The last example has "Item Dividers", which is on purpose, and is a special `li` used for separating groups of items. The current styling is correct.

2 - Each example says either "drop left", "drop right", "drop down", or "drop up". Unless I'm misunderstanding what your feedback is.

3 - The heading can be placed anywhere, it's not limited to being the 1st item. I can see how that would be confusing at first though, so I'll move it to the top.

Flex
1 - This is correct. This is how the flexbox spec works.

2 - The columns ordering, growing, and shrinking change between breakpoints, that's why the columns move around. As for the height on the 1st column, fixed it, nice catch.

Flyout
- I added some borders around each menu to make it easier to read.

- The flyout is also a bit problematic right now. I'm hoping to completely redo it for version 3.

**Comment by TraderStf** [comment]
Thanks for your answers, but it was not necessary, it is because I don't know how to write it in another way.

For Drop 1) only.
I'm not sure I was clear.

a) The dark-green background height is bigger than the light-green highlight, see rectangles.
In other words, highlight does not cover the entire lines, gap either on top or bottom.

b) The 'Item' string inside, see arrows: 
- first menu line/item it is verticaly-aligned on top
- second menu line/item it is vertically-aligned on bottom

![drophighlight arrows](https://cloud.githubusercontent.com/assets/5954335/6905446/4af9579c-d728-11e4-9fb2-b67eb776a502.png)



<i>(Just FYI, need to check and test. While testing Drop:
reload page, everything redraw than everything move up by ~3px, reproduced several times, then resize the window and no more move-up.)</i>

**Comment by TraderStf** [comment]
<h3>— Dimensions W x H on top-right of page —</h3>
Resize the window (using mouse pointer on bottom-right corner), 
then just Reload the page and the W and/or H is/are changed to (W and/or H) + 15px.
A second reload, just after the first one, does not change anything.
Probably scroll bars, but this happens when the scroll bars are visible or NOT!

980 x 860 become 995 x 860.
642 x 885 become 657 x 900.
889 x 965 become 904 x 965.
660 x 500 become 675 x 500.
1464 x 952 become 1479 x 952.

<h3>— Drop ups. Item dividers. Hover activated. —</h3>
The menu does not close if the mouse is outside the button or its menus.

<i>Dooo...</i> 🐌 <i>I just saw it is written 'item dividers' </i>

**Comment by TraderStf** [comment]
<h3>— No Style —</h3>

Sometimes, the page is shown without style.

Watch this movie: [nostyle.swf](https://www.moureau.me/4titon/2015-03-30-nostyle.swf)

Can reproduce this very often, not all the time, can't find any reason...
My line is stable and fast, 30-55 Mbps from USA to Belgium.

**Comment by TraderStf** [comment]
<h3>— Base —</h3>

Characters (and Bullets) are a bit weird... only <b>x</b> ????

**Comment by TraderStf** [comment]
<h3>— Carousel —</h3>
Few images would be nice, I can make some for you, nature, birds, monument, honey...pot... what you want.

1) Reduce the width of the window and all animation are ok but not the 16:9 block. It stops.
Must click on one of its two arrows to restart it.

**Comment by milesj** [comment]
In regards to the drop menus.

- The menu with the divider is actually 3 `li` elements, not 2. The "special" divider is used as such, a divider, so there is margin on the top and the bottom. The surrounding items are not off, as seen here (`li`s highlighted in red).

![890e12e6-d702-11e4-9199-c092041be492](https://cloud.githubusercontent.com/assets/143744/6908214/695e9590-d6f0-11e4-884e-990f68bfa341.png)

Also, it seems like some of the information you are asking for can be founds in the docs. The demo is purely for testing functionality. It's not supposed to represent "styling" as Toolkit is themeless.

**Comment by TraderStf** [comment]
<h3>— Drop —</h3>
For drop 2 only, here is what I try to say.

For the left: the first button, it appears below and for the second button it appears above.
Same for other blocks, except the first one "Default", both are below.
This seems a bit weird, add an explanation if it is intentional.

![dropleftdown](https://cloud.githubusercontent.com/assets/5954335/6908219/df782d22-d73b-11e4-95c5-5ed57b5cef90.png)
![drowrightup](https://cloud.githubusercontent.com/assets/5954335/6908222/e2863248-d73b-11e4-80c7-ec73bfb3af67.png)

**Comment by milesj** [comment]
The menus can be aligned on the main and cross axis, that's why they are shown differently. I'll put a note in.

**Comment by TraderStf** [comment]
>The menu with the divider is actually 3 li elements, not 2.

OK for me, it just seems a bug if it is not explained, as you said it 'demo.titon.io' I thought you plan to use it also for demo, not just testing.

**Comment by TraderStf** [comment]
I am going to sleep a bit :-) have a nice day and see you tomorrow. Thanks. Stf

**Comment by milesj** [comment]
Right now it is used for testing but there will be a more robust "demo" in the future. But until then, go ahead and keep sending any feedback, especially for things that don't make sense. I can easily update those.

**Comment by milesj** [comment]
Thanks for the feedback. Most, if not all of the feedback has been applied to the demos. Will be pushed soon.
