### ISSUE TITLE
demo.titon.io - 2015-03-31 Miscellaneous Remarks

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#122]
<h3>— Events Logged in Console —</h3>

Summary of all the components which log events in Safari Console.
<i>I don't think I have enabled somewhere the Debug switch (only the Debug menu is visible, need a third party tool to show it (or terminal command)).</i>

- Carousel
- Drop
- Flyout
- Input

**Comment by TraderStf** [comment]
<h3>— Form —</h3>

<i>For the Form, I must confirm if it is only in Titon-Toolkit, but I don't see that on github.</i>

- 'Input Text' have their 'Color' identical for Disabled, Read Only and Placeholder.

- Disabled text and Readonly text can be selected with a double-click and copied.

- Disabled does not have a focus (blue rectangle frame/border)

- Growbox not aligned
Text Area Grow box (bottom right corner) which appears has its left border not well aligned (1 pixel inside content area) when the scroll bar appears for the FIRST time. It also becomes well aligned after resizing the textarea.

e.g.: paste a long text, not aligned, cut/delete all the text, paste again, well aligned.

![textarea-growbox1](https://cloud.githubusercontent.com/assets/5954335/6916773/207d3534-d79f-11e4-8b14-229128f17b92.png)
![textarea-growbox2](https://cloud.githubusercontent.com/assets/5954335/6916775/229e6aea-d79f-11e4-8dd9-80a204c69b41.png)

- Two Lines Blinking
Resize the text area when there is a scroll bar, the bottom of the scroll bar (same width as grow box) and the right of the scroll bar are blinking, show/hide the blue frame.
The bottom blinks only when you in/decrease the height of the textarea.
The right blinks only when you in/decrease the width of the textarea.
Both when both sides are resized.

- Right of scroll bar in light-blue.
Sometimes, when you ends a resize, the right line/border of the scrollbox ? textarea frame is in a light-blue instead of the normal dark-blue. Capture: bottom in dark-blue, right is lighter.

![textarealightblue](https://cloud.githubusercontent.com/assets/5954335/6917258/4800060a-d7a3-11e4-9eb7-67e9f9ba67d1.png)

**Comment by TraderStf** [comment]
<h3>— Grid —</h3>

- Responsive Scaled Columns
On a wide page, 3 columns with same Height, it is ok.
When it reaches extra-small, the third column has a smaller height then the 2 first ones, perhaps normal their content is vertically-bigger.

![responsivescaledcolumns](https://cloud.githubusercontent.com/assets/5954335/6918570/2f7b4bc8-d7b0-11e4-932c-4d55cfec3fd6.png)

**Comment by TraderStf** [comment]
<h3>— Input —</h3>

- Checkboxes and radios
have different design than in previous components pages.
Others were in full bright blue, these are on very light blue, cyan instead of ✔︎ and ● marks.

- Non-expected Multiple Selects
I was able to get 2 highlighted menu items in the block 'Selects' or 'Select with option titles'.
Trying to reproduce... I think was create by a drag from the dropped menu.

**Comment by TraderStf** [comment]
<h3>— Lazy Load —</h3>

- I understand it but the demo is "not clear, not illustrative".
For Retina imagesss, I only have white squares with inside its top-left corner "Retina Image.", nothing else.

**Comment by TraderStf** [comment]
I stop this one and continue in another thread.

**Comment by milesj** [comment]
Thanks for the feedback. They have also been applied.
