### ISSUE TITLE
demo.titon.io - 2015-04-08 Miscellaneous Remarks

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#128]
<i>I have finished for today, the remaining components will be in another thread.</i>

<h3>— Mask —</h3>
1) Perhaps the second one 'Toggle Doc Mask' can show loader 3 sec then do something.
Here seems it is blocked.

2) font redraw
Don't know why, can not find the reason.
For Default masking, when the dark-mask disappear, the text/font seems to be drawn in 2 times.
A 'bit-jagged' font, then as it was anti-aliases.
Does not appear in Chrome.
For Doc Masking it seems to happen but it is faster, so don't see that jagged-then-clean font transition.

If it is a 'disolve' which is used, in Chrome you almost not see it at all, it is too fast.
In Safari, you see it, something like ~4 steps/levels, perhaps the reason of the jagged illusion.

**Comment by TraderStf** [comment]
<h3>— Matrix —</h3>
1) Some of the items/rectangles have the same color as the background.

2) Remove All items/rects first.
Seems that Append Item (sometimes Prepend Items) put the first item on the right, just as if there was already one on its left.
Resizing the window, make it moves to various place, left or right.

**Comment by TraderStf** [comment]
<h3>— Modal —</h3>

1) Other language in Form
The area to choose a file, is in French.
![10](https://cloud.githubusercontent.com/assets/5954335/7045397/0bb13d02-ddfe-11e4-8a87-51988a04cc80.png)

2)

**Comment by TraderStf** [comment]
<h3>— Notice —</h3>
A small note explaining can have ? color, close button...

**Comment by TraderStf** [comment]
<h3>— Off Canvas —</h3>
Add in the correct order, Choose an animation, then click... :-)

The sidebars are appearing over the Black-Top area of the page, without moving/resizing it.
The contents below, grey area, is correctly resized.

**Comment by TraderStf** [comment]
<h3>— Pagination —</h3>
nihil

<h3>— Pin —</h3>
For the first one, sometimes (with smallest window's width) the Pin goes up during the scroll before reaching the bottom of the text on the left.

![11](https://cloud.githubusercontent.com/assets/5954335/7045941/99ada650-de02-11e4-8f11-a9fccd42075a.png)

**Comment by TraderStf** [comment]
<h3>— Popover —</h3>

If window is resized, they do not follow/change.

**Comment by TraderStf** [comment]
<h3>— Showcase —</h3>

The number inside the boxes are "weird"... not corresponding to those visible.

FYI, the box's inside text do not have the jagged edges problem, see above Mask-2 and Matrix-3.

**Comment by TraderStf** [comment]
<h3>— Stalker —</h3>

Bad display.

![default](https://cloud.githubusercontent.com/assets/5954335/7046965/a31d91d0-de09-11e4-93e9-8819cbc2cd01.png)

**Comment by TraderStf** [comment]
<h3>— Step —</h3>

1) Different rendering
Sometimes the second line is yellow, sometimes orange.

![6](https://cloud.githubusercontent.com/assets/5954335/7047153/0fd920a4-de0b-11e4-8701-de492b5fe8b3.png)

Don't know if it is possible, after the last item on a second line (step 5 on bigger in capture) it would be better to not see the orange background, but just ending by the 'usual' right yellow side of the S5.

**Comment by TraderStf** [comment]
Hello,
About the various items which are first draw with jagged edges then cleanly redrawn, it seems to be in several sites, may be all, should test if it is my mac as I tweak him quite a lot, some features are not recommended.
Have a nice day :-)

**Comment by milesj** [comment]
Thanks for the feedback! Most of the changes have been applied to the demos.

In regards to the jagged text, it seems like it may be a browser issue, as I an reproduce it as well.
