### ISSUE TITLE
Libsass Error

### ISSUE THREAD

**Issue by christianmagill** [titon/toolkit#140]
I get the following error compiling with Libsass 3.2.2

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ←[4massets\vendor\toolkit\scss\toolkit\mixins\_layout.scss←[24m
←[90m  83:6←[39m  invalid selector after

**Comment by milesj** [comment]
What node-sass version are you using?

I'm using libsass 3.1 and node-sass 2.1. I wonder if something changed in the newest major version.

**Comment by christianmagill** [comment]
That's the complete error. This recent Libsass update was pretty significant.

From node-sass package.json

  "name": "node-sass",
  "version": "3.0.0",
  "libsass": "3.2.2",

**Comment by milesj** [comment]
Yeah must be a change in 3.0. I'll update the package and give it a look.

**Comment by milesj** [comment]
Looks to be a problem with merging lists: https://github.com/sass/libsass/issues/1122#issuecomment-96752830

**Comment by milesj** [comment]
I fixed this in the 2.1 branch. Will tag it later today.

Feel free to test this branch in the mean time.

**Comment by christianmagill** [comment]
Thanks, Anything I need to do to get it working with bower?

**Comment by christianmagill** [comment]
I tried 
bower install toolkit#2.1 --save

**Comment by christianmagill** [comment]
Pulled in via git.. seems to be working well.

**Comment by milesj** [comment]
Awesome, thanks for testing! And the report of course.

**Comment by milesj** [comment]
Tagged 2.1.4.
