### ISSUE TITLE
[2.1] off canvas animation issue

### ISSUE THREAD

**Issue by nor-bu** [titon/toolkit#143]
hey,

i think i found a bug with the scss files.
when i work with the off-canvas demo from the components folder i have the follow issue.

off canves works fine but the animation works not correct, the the main content will not pushed and all animations not smooth.
when i replace the off-canves.scss file with the plain css section from the toolkit.css then works fine.

how can i fix this in scss files?

PS: all other animations works fine with scss files

thanks for help

**Comment by milesj** [comment]
What animations do you have enabled in `$offCanvas-animations`? Also, what does your markup look like?

**Comment by nor-bu** [comment]
i have all animations enabled. My markup is the file from toolkit repo demo folder.

**Comment by milesj** [comment]
Anyway you can put it online somewhere so I can take a look? Perhaps Codepen?

**Comment by nor-bu** [comment]
i made a example. can you give my your mail address?

**Comment by milesj** [comment]
mileswjohnson+titon [at] gmail [dot] com

**Comment by milesj** [comment]
I replied to your email.

**Comment by milesj** [comment]
@nor-bu Had a chance to look at this? Want to tag a new version soon.

**Comment by milesj** [comment]
Marking this closed.
