### ISSUE TITLE
modal show from js 

### ISSUE THREAD

**Issue by nor-bu** [titon/toolkit#151]
hi,

how can i cal the modal from a js file?

thanks for help

**Comment by milesj** [comment]
You'd have to access the modal instance and then call the `show()` method.

* http://titon.io/en/toolkit/2.1.5/development/js/usage#accessing-instances
* http://titon.io/en/toolkit/2.1.5/components/modal#usage

**Comment by nor-bu** [comment]
thanks for your answer, but that not work.

when i call the show method, shows the modal without content, only the loading state.
how is my mistake?

i want call the modal without a href tag


my html:
```
<button id="show-menu" class="button js-modal"><i class="fa fa-bars fa-2x"></i><span>Menu</span></button>

    <div id="menu" class="hidden">
        <div class="modal-head">
            <h4>Menu</h4>
        </div>

        <div class="modal-body">
            The content of this modal was loaded through a hidden DOM element and inserted into the modal.
        </div>
    </div>
```

my js:

```
 var modal = $('.js-modal').modal({
        getContent:'#menu'
    }).toolkit('modal');

    modal.show();
```

**Comment by milesj** [comment]
The `getContent` option isn't the content to place in the modal, it's the attribute on the node in which to *find* the content.

You would need to do this.

```javascript
modal.show(
    $('#show-menu'), // The element that opened it
    $('#menu').html() // The content to show in the modal
);
```

However, if you are using `getContent` correctly, which defaults to `data-modal`, you can simply change your markup to the following.

```html
<button id="show-menu" class="button js-modal" data-modal="#menu"><i class="fa fa-bars fa-2x"></i><span>Menu</span></button>

...
```
