### ISSUE TITLE
The styling of carousels seems to rely on `float` rather than `inline-block`

### ISSUE THREAD

**Issue by thierryk** [titon/toolkit#159]
`inline-block` is a better construct than `float` when it comes to styling carousels. This is because `inline-block` allows to create a **container** that can be of the same with of the "_view_" (the visible part of the carousel). In other words, it allows to rely on CSS **instead of JavaScript** for width calculation&mdash;see [styling effective carousels](http://cssmojo.com/how-to-style-a-carousel/).

**Comment by milesj** [comment]
Interesting, thanks for this. Haven't seen it before.

The new Carousel in 3.0 has been rewritten using flexbox, but perhaps this might work better. Will give it a try.

**Comment by milesj** [comment]
This seems to work perfectly with flexbox. Thanks a lot for this, made the code much easier to use.

https://github.com/titon/toolkit/commit/b075c9499775c104b8cd6fd40c571a5575806443

**Comment by milesj** [comment]
This has been updated in the 3.0 branch. Will not backport due to legacy issues.
