### ISSUE TITLE
Error $.access is not a function

### ISSUE THREAD

**Issue by christianmagill** [titon/toolkit#167]
I'm getting this error with a WordPress site using jQuery v1.12.3 and jQuery Migrate v1.4.0

I can't seem to find any reference to an $.access method in jQuery documentation or in the in the toolkit file except to it's usage below.

https://github.com/titon/toolkit/blob/3.0/dist/toolkit.js#L578

**Comment by milesj** [comment]
Thanks for the report. The method in jQuery can be found here: https://github.com/jquery/jquery/blob/055cb7534e2dcf7ee8ad145be83cb2d74b5331c7/src/core/access.js

Basically `$.access()` allows for getting and setting of values, think `attr()`.

What version of jQuery are you using? I wonder if they removed it from the public API.

**Comment by christianmagill** [comment]
WordPress site using jQuery v1.12.3 and jQuery Migrate v1.4.0

**Comment by milesj** [comment]
It looks like it existed in 1.9, so it must have been removed sometime in between then: https://github.com/jquery/jquery/blob/055cb7534e2dcf7ee8ad145be83cb2d74b5331c7/test/data/jquery-1.9.1.js#L847

I guess I'll have to patch a work around.

**Comment by christianmagill** [comment]
Thanks

**Comment by milesj** [comment]
Yup, looks like it was removed in 1.12: https://github.com/jquery/jquery/issues/2513

**Comment by milesj** [comment]
I removed `$.access()` in 2.1.9.

https://github.com/titon/toolkit/commit/06ac65a9525bf5ada0716792d812050d6031d1bf

**Comment by christianmagill** [comment]
Thanks!

**Comment by milesj** [comment]
Sure, no problem!
