### ISSUE TITLE
Alignment in RTL mode

### ISSUE THREAD

**Issue by adusak** [titon/toolkit#170]
Hello, I have a question about the alignments.

When I am displaying a page in RTL mode the alignments don't get switched. Meaning even if the UI should be completely fliped it is not because of the align (and float) classes being the same in both the base css and the rtl css.

Is this the expected behaviour?

**Comment by milesj** [comment]
Hey adusak,

Are you using the RTL specific CSS file? https://github.com/titon/toolkit/blob/3.0/dist/toolkit-rtl.css

That would have all the alignment properties reversed.

**Comment by adusak** [comment]
Yes I am, although I am using version 2.1.8.

Let me demonstrate what I mean using the demo site:

This is how alignment looks when the mode is switched to RTL:
![howitis](https://cloud.githubusercontent.com/assets/1461364/15121525/5eaab622-161b-11e6-8ed9-fc8e2d41cde9.png)

And this is how I would expect it to look:
![howiexpectit](https://cloud.githubusercontent.com/assets/1461364/15121607/a50d6d1c-161b-11e6-84c8-913231c92a1b.png)

Does this make sense? Thanks for your reply.

**Comment by milesj** [comment]
Ahh, ok. Yeah, the `align-left` and `align-right` classes are fixed and don't respect the RTL mode. I can see how this could be a problem. I don't plan on fixing this in the v2 branch, as in the v3 I will be adding a `align-start` and `align-end` that does support RTL.

I'd suggest adding your own classes for to solve this issue for now.

Are there any other cases where the RTL doesn't work?

**Comment by adusak** [comment]
I figured that those classes would probably get added as they make more sense than actually flipping left and right.
I have noticed the same behavior with the float classes. Other than than I haven't found anything, if I do I'll be sure to report it.

Thank you.

**Comment by milesj** [comment]
Yeah, the align and float classes in the base styles are all fixed: https://github.com/titon/toolkit/blob/2.1/scss/toolkit/base.scss#L17

Forgot about the float ones. Look like I'll be adding `float-start` and `float-end` also.

**Comment by milesj** [comment]
I decided to add these as I was fixing some other issues. Is available in 2.1.9.

https://github.com/titon/toolkit/commit/625244346338587fb63aefa840526e30dc93edeb
