### ISSUE TITLE
Bootstrap Modal Does Not work with toolkit include

### ISSUE THREAD

**Issue by jaypsingh** [titon/toolkit#210]
I am facing a problem with toolkit.css and i was hoping if you could help.
 
I am trying to implement modal on my page using Bootstrap4 (the alpha version).
But as soon as i include toolkit.min.css bootstrap modal does not work. 
<link rel="stylesheet" type="text/css", href="css/toolkit.min.css">
(toolkit is awesome and i really reallyyy would love to include these)

I checked that by creating a very simple page that just includes [basic starter template of bootstrap](https://getbootstrap.com/docs/4.0/getting-started/introduction/) and toolkit.min.js and toolkit.min.css. 
I added the code to launch very simple modal in my test. 

I have attached the test package for your reference (html, toolkit css and toolkit js) .

I have verified this on toolkit version 2.1.0 and 2.0.0. I saw similar issues with both. 
[Test_Files.zip](https://github.com/titon/toolkit/files/1309615/Test_Files.zip)
I also saw the problem on chrome (Version 60.0.3112.113 ), firefox (V52.3) and IE 11

Thanks and Regards,
Jay

**Comment by jaypsingh** [comment]
I was **able to resolve this by commenting the below line(s)** of code in the toolkit.css file:
.modal {
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  visibility: hidden;
  z-index: 610;
  overflow: auto;
  transition: opacity 0.3s, visibility 0.3s;
  -webkit-overflow-scrolling: touch;
}

After commenting this there was no problem in launching the modal.

Thanks and Regards,
Jay

**Comment by milesj** [comment]
@jaypsingh Yeah, that'll do it. I suggest namespacing your CSS: http://titon.io/en/toolkit/2.1.6/development/namespace

**Comment by jaypsingh** [comment]
@milesj Thanks you.
