### ISSUE TITLE
[2.1] JS BEM Separator Support 

### ISSUE THREAD

**Issue by christianmagill** [titon/toolkit#82]
Not sure how wide range this would be, but with the BEM separator customization, items that are generated by JavaScript do not currently get the customized separator. I guess alternate templates could be provided, but perhaps this is something that could be set in the base Toolkit.Component object.

**Comment by milesj** [comment]
Having trouble getting this working without a major rewrite. If I add a custom `bem()` function that generates class names, and inject it into each `template`, they will be built before the BEM separators can be overwritten.

Any approach I go with would blow up the filesize greatly. This will probably have to be pushed back until we start using real templates that are rendered.

**Comment by milesj** [comment]
Figured out a way to handle this.
