### ISSUE TITLE
[2.1] Tooltip/Popover get stuck sometimes

### ISSUE THREAD

**Issue by mmiloshev** [titon/toolkit#97]
When I move fast over the tooltip it's open and doesn't disapear. It's get stuck and you need to click again to close. I using 2.0.1 version. I also try 2.0.2 ver. on http://demo.titon.io/ site, and the problem still exist.

![issue](https://cloud.githubusercontent.com/assets/10066873/5901069/ab6d8390-a56f-11e4-867b-ca60778e9d03.JPG)

**Comment by mmiloshev** [comment]
Update: Everything works fine in Opera, IE 11 and Chrome. The problem only exist in Mozila Firefox.

**Comment by milesj** [comment]
Thanks for pointing it out. I've actually refactored all the tooltip/popover code in the 2.1 branch, so hopefully those changes mitigate this issue.

**Comment by milesj** [comment]
This has been fixed in 2.1.
